"""Local image collection helpers for audit inputs and MinerU artifacts."""

import re
from pathlib import Path
from typing import Iterable, List

from .file_utils import _safe_name

DEFAULT_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".tiff", ".tif", ".webp"}
DEFAULT_MIN_IMAGE_BYTES = 5000

__all__ = [
    "DEFAULT_IMAGE_EXTENSIONS",
    "DEFAULT_MIN_IMAGE_BYTES",
    "_dedupe_paths",
    "_image_output_dir",
    "_extract_images_from_mineru_zip",
    "_extract_images_from_mineru_zip_from_namespace",
    "collect_mineru_image_files",
    "collect_mineru_image_files_from_namespace",
    "_latest_mineru_zips",
]


def _namespace_value(namespace, name, default=None):
    if isinstance(namespace, dict):
        return namespace.get(name, default)
    return getattr(namespace, name, default)


def _dedupe_paths(paths: Iterable) -> List[str]:
    seen = set()
    result = []
    for path in paths:
        try:
            resolved = str(Path(path).resolve())
        except Exception:
            resolved = str(path)
        if resolved not in seen:
            seen.add(resolved)
            result.append(resolved)
    return result


def _image_output_dir(input_path: str):
    p = Path(input_path)
    if p.is_file():
        return p.parent / "_paper_audit_images"
    return p / "_paper_audit_images"


def _extract_images_from_mineru_zip(
    zip_path: Path,
    output_dir: Path,
    image_extensions=None,
    min_image_bytes=DEFAULT_MIN_IMAGE_BYTES,
) -> List[str]:
    images = []
    extensions = set(image_extensions or DEFAULT_IMAGE_EXTENSIONS)
    try:
        import zipfile

        output_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(zip_path) as zf:
            for name in zf.namelist():
                suffix = Path(name).suffix.lower()
                if suffix not in extensions:
                    continue
                info = zf.getinfo(name)
                if info.file_size < min_image_bytes:
                    continue
                out_name = f"{_safe_name(zip_path.stem)}_{_safe_name(Path(name).stem)}{suffix}"
                out_path = output_dir / out_name
                out_path.write_bytes(zf.read(name))
                images.append(str(out_path))
    except Exception as e:
        print(f"  ⚠️ MinerU图片提取失败 {zip_path}: {e}")
    return images


def _extract_images_from_mineru_zip_from_namespace(namespace, zip_path: Path, output_dir: Path) -> List[str]:
    return _extract_images_from_mineru_zip(
        zip_path,
        output_dir,
        image_extensions=_namespace_value(namespace, "IMAGE_EXTENSIONS", DEFAULT_IMAGE_EXTENSIONS),
        min_image_bytes=_namespace_value(namespace, "MIN_IMAGE_BYTES", DEFAULT_MIN_IMAGE_BYTES),
    )


def collect_mineru_image_files(
    input_path: str,
    output_dir=None,
    image_extensions=None,
    min_image_bytes=DEFAULT_MIN_IMAGE_BYTES,
) -> List[str]:
    """Collect images saved inside MinerU zip artifacts generated by extraction."""
    extensions = set(image_extensions or DEFAULT_IMAGE_EXTENSIONS)
    p = Path(input_path)
    base = Path(output_dir) if output_dir else (p.parent if p.is_file() else p)
    zips = []
    if base.exists():
        zips.extend(base.glob("*.mineru.zip"))
    if p.is_dir():
        zips.extend(p.rglob("*.mineru.zip"))
    zips = _latest_mineru_zips(zips)
    images_dir = _image_output_dir(str(p))
    images = []
    for zip_path in _dedupe_paths(zips):
        images.extend(
            _extract_images_from_mineru_zip(
                Path(zip_path),
                images_dir,
                image_extensions=extensions,
                min_image_bytes=min_image_bytes,
            )
        )
    if zips:
        return _dedupe_paths(images)
    if images_dir.exists():
        for ext in extensions:
            for image_path in images_dir.rglob(f"*{ext}"):
                try:
                    if image_path.stat().st_size >= min_image_bytes:
                        images.append(str(image_path))
                except Exception:
                    continue
    return _dedupe_paths(images)


def collect_mineru_image_files_from_namespace(namespace, input_path: str, output_dir=None) -> List[str]:
    return collect_mineru_image_files(
        input_path,
        output_dir=output_dir,
        image_extensions=_namespace_value(namespace, "IMAGE_EXTENSIONS", DEFAULT_IMAGE_EXTENSIONS),
        min_image_bytes=_namespace_value(namespace, "MIN_IMAGE_BYTES", DEFAULT_MIN_IMAGE_BYTES),
    )


def _latest_mineru_zips(paths):
    latest = {}
    for path in paths:
        p = Path(path)
        name = p.name
        if not name.endswith(".mineru.zip"):
            continue
        key = name[: -len(".mineru.zip")]
        key = re.sub(r"\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "", key, flags=re.I)
        try:
            mtime = p.stat().st_mtime
        except Exception:
            mtime = 0
        current = latest.get(key)
        if current is None or mtime > current[0]:
            latest[key] = (mtime, str(p))
    return [item[1] for item in latest.values()]
